name: cabal

on:
  push:
    branches: [ci-cabal, develop, add/haddocks-13, wip/build-matrix]
  pull_request:
    branches: [master]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.4"]
        ghc:
          - "8.6.5"
          - "8.8.4"
          - "8.10.4"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-haskell@v1
      name: setup GHC and cabal-install
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v1
      name: cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - name: build
      run: |
        cabal v2-update
        cabal v2-build all

    - name: simple
      run: cabal v2-test chromar:test:simple --test-show-details=direct --test-option="--color=always"

    - name: hlint
      run: cabal v2-test chromar:test:hlint --test-show-details=direct --test-option="--color=always"

    - name: doctest
      run: cabal v2-test chromar:test:doctest --test-show-details=direct --test-option="--color=always"
